const assert = require('assert');
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');
const html = fs.readFileSync(path.join(root, 'hanafuda', 'index.html'), 'utf8');
const css = fs.readFileSync(path.join(root, 'hanafuda', 'styles.css'), 'utf8');
const multiplayerCss = fs.readFileSync(path.join(root, 'multiplayer.css'), 'utf8');
const app = fs.readFileSync(path.join(root, 'hanafuda', 'app.js'), 'utf8');
const engine = fs.readFileSync(path.join(root, 'hanafuda', 'engine.js'), 'utf8');
for (const id of ['field-cards', 'draw-pile', 'local-hand', 'capture-modal', 'btn-koi', 'btn-shobu', 'spectator-controls', 'chat-drawer']) assert(html.includes(`id="${id}"`), `Missing ${id}`);
assert(html.includes('value="3"') && html.includes('value="6"') && html.includes('value="12"'));
assert(html.includes('#EF1D1E') && html.includes('id="viewing-yaku"') && html.includes('id="busted-viewing"'));
assert(css.includes('height: 100svh') && !app.includes("window.addEventListener('resize'"), 'Mobile table must not jump on browser chrome resizes');
assert(css.includes('@media (max-height: 680px) and (orientation: landscape)'));
assert(engine.includes('delete state.deck') && app.includes('getViewState(perspectiveId, spectator)'));
assert(app.includes("RoomTools.configureInvite('hanafuda', peerId,") && app.includes("RoomTools.resolveJoinId('hanafuda'") && html.includes('id="btn-copy-invite"'));
assert(html.includes('value="invert"') && html.includes('value="white-red"'), 'Hanafuda needs readable artwork modes for dark SVGs');
assert(css.includes('border: 2px solid #ef1d1e') && css.includes('object-fit: contain') && css.includes('.hana-card:has(.hana-art) .hana-face { background: #fff; }'), 'Hanafuda SVG fronts must sit on a white face with a red border without being cropped');
assert(css.includes('background: transparent') && !css.includes('background: #0b0b0a'), 'Transparent Hanafuda artwork must not inherit a black image-layer background');
assert(multiplayerCss.includes('#qr-container img, #qr-container canvas { display: block; width: 100% !important; height: 100% !important;'), 'The generated QR must exactly fill its holder');
assert(multiplayerCss.includes('padding: 4px; box-sizing: border-box; background: white;'), 'The full-size QR needs an internal white quiet zone for reliable scanning');
assert(html.includes('class="back-to-games"') && html.includes('class="table-game-selection"'), 'Hanafuda needs a direct route back to game selection from lobby and table');
assert(app.includes('UI.syncModalOverlay()') && app.includes('UI.hideResult(); Net.sendAction'), 'Advancing a month must remove the iOS blur overlay before dealing');
assert(app.includes("player.connected === false ? 'REMOVE' : 'KICK'"), 'Hanafuda hosts must be able to remove an abandoned second seat and invite a replacement');
for (const phrase of ['What am I trying to do?', 'What happens on my turn?', 'Example:', 'Koi-Koi means', 'Last turn and an empty round']) assert(html.includes(phrase), `Easy Hanafuda guide is missing: ${phrase}`);
assert(html.includes('src="rules.js"') && html.includes('src="engine.js"') && html.includes('src="bots.js"'));
for (const other of ['../index.html?game=bazunga', '../president/index.html?game=president', '../durak/index.html?game=durak']) assert(html.includes(other));
console.log('Hanafuda UI: isolated routing, stable mobile table, Yaku actions, art/back settings, P2P privacy, spectator, and chat passed.');
